CREATE DATABASE AUXILIUMDB();

CREATE TABLE USUARIO(
	
	ID_USUARIO INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME_USUARIO VARCHAR(40) NOT NULL UNIQUE KEY,
	EMAIL_USUARIO VARCHAR(60) NOT NULL UNIQUE KEY,
	SENHA_USUARIO VARCHAR(80) NOT NULL,
	IMAGEM_USUARIO LONGBLOB, 
	CEP_USUARIO VARCHAR(9) NOT NULL,
	ENDERECO_USUARIO VARCHAR(80) NOT NULL,
	NUMRESIDENCIA_USUARIO INT(6) NOT NULL,
	COMPLEMENTO_USUARIO VARCHAR(35),	
	RANK_USUARIO INT(2) NOT NULL

);

CREATE TABLE CURSO(
	
	ID_CURSO INT(20) AUTO_INCREMENT PRIMARY KEY,
	TITULO_CURSO VARCHAR(80) NOT NULL,
	NOME_USUARIO VARCHAR(40) NOT NULL,
	DESCRICAO_CURSO VARCHAR(280) NOT NULL,
	IMAGEM_CURSO LONGBLOB,
	VALOR_CURSO FLOAT(2) NOT NULL,
	
	CONSTRAINT FOREIGN KEY (NOME_USUARIO) REFERENCES USUARIO(NOME_USUARIO)
	
);

CREATE TABLE COMPRA(
	
	ID_COMPRA INT(20) AUTO_INCREMENT PRIMARY KEY,
	ID_USUARIO INT(20),
	ID_CURSO INT(20),
	VALOR_COMPRA FLOAT(2) NOT NULL,
	DATA_COMPRA DATE NOT NULL,
    
    CONSTRAINT FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)    
    
);

CREATE TABLE NIVEL(

	ID_NIVEL INT(20) AUTO_INCREMENT PRIMARY KEY,
	ID_CURSO INT(20),
	TITULO_NIVEL VARCHAR(80) NOT NULL,
	
	CONSTRAINT FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)

);

CREATE TABLE MODULO(

	ID_MODULO INT(20) AUTO_INCREMENT PRIMARY KEY,
	ID_NIVEL INT(20),
	TITULO_MODULO VARCHAR(80) NOT NULL,
	DESCRICAO_MODULO VARCHAR(280) NOT NULL,
	ARQUIVO_MODULO LONGBLOB NOT NULL,
	
	CONSTRAINT FOREIGN KEY (ID_NIVEL) REFERENCES NIVEL(ID_NIVEL)
	
);