CREATE TABLE COMPRA(
	
	ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
	ID_USUARIO INT,
	ID_CURSO INT,
	VALOR_COMPRA FLOAT(2) NOT NULL,
	DATA_COMPRA DATE NOT NULL,
	VENCIMENTO_COMPRA DATE NOT NULL,
    
    CONSTRAINT FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)    
    
);