CREATE TABLE COMPRA(
	
	ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
	ID_USUARIO INT,
	VALOR_COMPRA FLOAT(2) NOT NULL,
	DATA_COMPRA TIMESTAMP default current_timestamp(),
	VENCIMENTO_COMPRA TEXT NOT NULL,
	VERIFICACAO_COMPRA INT(1) NOT NULL,
    
    CONSTRAINT FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
    
);