CREATE TABLE COMPRA(
	
	ID_COMPRA INT(20) AUTO_INCREMENT PRIMARY KEY,
	ID_USUARIO INT(20),
	ID_CURSO INT(20),
	VALOR_COMPRA FLOAT(2) NOT NULL,
	DATA_COMPRA DATE NOT NULL,
    
    CONSTRAINT FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)    
    
);