CREATE TABLE CURSO(
	
	ID_CURSO INT(20) AUTO_INCREMENT PRIMARY KEY,
	TITULO_CURSO VARCHAR(80) NOT NULL,
	NOME_USUARIO VARCHAR(40) NOT NULL,
	IMAGEM_USUARIO LONGBLOB, 
	DESCRICAO_CURSO VARCHAR(280) NOT NULL,
	/* IMAGEM_CURSO LONGBLOB, */
	VALOR_CURSO FLOAT(2) NOT NULL,
	
	CONSTRAINT FOREIGN KEY (NOME_USUARIO) REFERENCES usuario(NOME_USUARIO),
	/* CONSTRAINT FOREIGN KEY (IMAGEM_USUARIO) REFERENCES usuario(IMAGEM_USUARIO) */
	
);