CREATE TABLE CURSO(
	
	ID_CURSO INT AUTO_INCREMENT PRIMARY KEY,
	ID_USUARIO INT,
	TITULO_CURSO VARCHAR(80) NOT NULL,	
	DESCRICAO_CURSO VARCHAR(280) NOT NULL,
	TEMPOESTIMADO_CURSO INT(3) NOT NULL,
	IMAGEM_CURSO LONGBLOB,
	
	CONSTRAINT FOREIGN KEY (ID_USUARIO) REFERENCES usuario(ID_USUARIO)
	
);