CREATE TABLE MODULO(

	ID_MODULO INT AUTO_INCREMENT PRIMARY KEY,
	ID_NIVEL INT,
	TITULO_MODULO VARCHAR(60) NOT NULL,
	DESCRICAO_MODULO VARCHAR(280) NOT NULL,
	
	CONSTRAINT FOREIGN KEY (ID_NIVEL) REFERENCES NIVEL(ID_NIVEL)
	
);