CREATE TABLE MODULO(

	ID_MODULO INT(20) AUTO_INCREMENT PRIMARY KEY,
	ID_NIVEL INT(20),
	TITULO_MODULO VARCHAR(80) NOT NULL,
	DESCRICAO_MODULO VARCHAR(280) NOT NULL,
	ARQUIVO_MODULO LONGBLOB NOT NULL,
	
	CONSTRAINT FOREIGN KEY (ID_NIVEL) REFERENCES NIVEL(ID_NIVEL)
	
);