CREATE DATABASE auxiliumDB CHARACTER SET utf8 COLLATE utf8_general_ci;

USE auxiliumDB;

CREATE TABLE USUARIO(
	
	ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
	NOME_USUARIO VARCHAR(60) NOT NULL,
	APELIDO_USUARIO VARCHAR(20) NOT NULL UNIQUE KEY,
	EMAIL_USUARIO VARCHAR(40) NOT NULL UNIQUE KEY,
	SENHA_USUARIO VARCHAR(180) NOT NULL,
	IMAGEM_USUARIO LONGBLOB, 
	CEP_USUARIO VARCHAR(9) NOT NULL,
	ESTADO_USUARIO VARCHAR(30) NOT NULL,
	CIDADE_USUARIO VARCHAR(40) NOT NULL,
	BAIRRO_USUARIO VARCHAR(30) NOT NULL,
	ENDERECO_USUARIO VARCHAR(40) NOT NULL,
	NUMRESIDENCIA_USUARIO INT(5) NOT NULL,
	COMPLEMENTO_USUARIO VARCHAR(20),	
	RANK_USUARIO INT(2) NOT NULL

);

CREATE TABLE CURSO(
	
	ID_CURSO INT AUTO_INCREMENT PRIMARY KEY,
	ID_USUARIO INT,
	TITULO_CURSO VARCHAR(80) NOT NULL,	
	DESCRICAO_CURSO VARCHAR(280) NOT NULL,
	TEMPOESTIMADO_CURSO INT(3) NOT NULL,
	IMAGEM_CURSO LONGBLOB,
	
	CONSTRAINT FOREIGN KEY (ID_USUARIO) REFERENCES usuario(ID_USUARIO)
	
);

CREATE TABLE COMPRA(
	
	ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
	ID_USUARIO INT,
	VALOR_COMPRA FLOAT(2) NOT NULL,
	DATA_COMPRA DATE NOT NULL,
	VENCIMENTO_COMPRA DATE NOT NULL,
	VERIFICACAO_COMPRA INT(1) NOT NULL,
    
    CONSTRAINT FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
    
);

CREATE TABLE NIVEL(

	ID_NIVEL INT AUTO_INCREMENT PRIMARY KEY,
	ID_CURSO INT,
	TITULO_NIVEL VARCHAR(60) NOT NULL,
	
	CONSTRAINT FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)

);

CREATE TABLE MODULO(

	ID_MODULO INT AUTO_INCREMENT PRIMARY KEY,
	ID_NIVEL INT,
	TITULO_MODULO VARCHAR(60) NOT NULL,
	DESCRICAO_MODULO VARCHAR(280) NOT NULL,
	
	CONSTRAINT FOREIGN KEY (ID_NIVEL) REFERENCES NIVEL(ID_NIVEL)
	
);

CREATE TABLE CONTEUDO(

	ID_CONTEUDO INT AUTO_INCREMENT PRIMARY KEY,
    ID_MODULO INT,
	CONTEUDO_CONTEUDO LONGBLOB,
    CONSTRAINT FOREIGN KEY (ID_MODULO) REFERENCES MODULO(ID_MODULO)

);