CREATE TABLE USUARIO(
	
	ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
	NOME_USUARIO VARCHAR(60) NOT NULL,
	APELIDO_USUARIO VARCHAR(20) NOT NULL UNIQUE KEY,
	EMAIL_USUARIO VARCHAR(40) NOT NULL UNIQUE KEY,
	SENHA_USUARIO VARCHAR(80) NOT NULL,
	IMAGEM_USUARIO LONGBLOB, 
	CEP_USUARIO VARCHAR(9) NOT NULL,
	ESTADO_USUARIO VARCHAR(30) NOT NULL,
	CIDADE_USUARIO VARCHAR(40) NOT NULL,
	BAIRRO_USUARIO VARCHAR(30) NOT NULL,
	ENDERECO_USUARIO VARCHAR(40) NOT NULL,
	NUMRESIDENCIA_USUARIO INT(5) NOT NULL,
	COMPLEMENTO_USUARIO VARCHAR(20),	
	RANK_USUARIO INT(2) NOT NULL

);