CREATE TABLE USUARIO(
	
	ID_USUARIO INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME_USUARIO VARCHAR(40) NOT NULL UNIQUE KEY,
	EMAIL_USUARIO VARCHAR(60) NOT NULL UNIQUE KEY,
	SENHA_USUARIO VARCHAR(80) NOT NULL,
	IMAGEM_USUARIO LONGBLOB, 
	CEP_USUARIO VARCHAR(9) NOT NULL,
	ENDERECO_USUARIO VARCHAR(80) NOT NULL,
	NUMRESIDENCIA_USUARIO INT(6) NOT NULL,
	COMPLEMENTO_USUARIO VARCHAR(35),	
	RANK_USUARIO INT(2) NOT NULL

);